---
.molecule:
  tags: [ffci]
  only: [/^pr-.*$/]
  except: ['triggers']
  stage: deploy-part1
  image: $PIPELINE_IMAGE
  needs:
  - pipeline-image
  # - ci-not-authorized
  script:
  - ./tests/scripts/molecule_run.sh
  after_script:
  - ./tests/scripts/molecule_logs.sh
  artifacts:
    when: always
    paths:
    - molecule_logs/

molecule:
  extends: .molecule
  script:
  - ./tests/scripts/molecule_run.sh -i $ROLE
  parallel:
    matrix:
    - ROLE:
      - container-engine/cri-dockerd
      - container-engine/containerd
      - container-engine/cri-o
      - adduser
      - bastion-ssh-config
      - bootstrap-os

# CI template for periodic CI jobs
# Enabled when PERIODIC_CI_ENABLED var is set
molecule_full:
  only:
    variables:
    - $PERIODIC_CI_ENABLED
  allow_failure: true
  extends: molecule
  parallel:
    matrix:
    - ROLE:
      - container-engine/cri-dockerd
      - container-engine/containerd
      - container-engine/cri-o
      - adduser
      - bastion-ssh-config
      - bootstrap-os
      # FIXME : tests below are perma-failing
      - container-engine/kata-containers
      - container-engine/gvisor
      - container-engine/youki
